### ISSUE TITLE
--build-arg support

### ISSUE THREAD

**Issue by squarebracket** [jerray/publish-docker-action#1]
This is a great action, thanks for sharing it.

Is there any chance you could add `--build-arg` support? Unfortunately, I'm pretty useless at go, otherwise I'd make a PR.

From what I can tell, `github.com/caarlos0/env` supports a json type, so the yaml input could be a json string, I think.

**Comment by jerray** [comment]
Thanks for opening the first issue.
I will work around with this later when I have spare time.

**Comment by jerray** [comment]
```yaml
- uses: jerray/publish-docker-action@master
  with:
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}
    registry: docker.pkg.github.com
    repository: jerray/publish-docker-action
    tags: latest,newest,master
    build_args: HTTP_RROXY=http://127.0.0.1:8080,USER=nginx
```

@squarebracket  I'm considering implement this feature. Same as `tags` argument, multiple build args can be separated by commas. Does this satisfy your need ?

**Comment by squarebracket** [comment]
This is great, thanks!

Works for both:
```
        with:
          build_args: JDK_VERSION=${{ matrix.jdk }},CI_PROJECT_URL=https://github.com/${{ github.repository }}
```
and
```
        with:
          build_args: JDK_VERSION,CI_PROJECT_URL
        env:
          JDK_VERSION: ${{ matrix.jdk }}
          CI_PROJECT_URL: https://github.com/${{ github.repository }}
```
I'm not sure if you think the second form is worthwhile to mention in the README, or if you think it's self-evident from the first, but I find the separate `env` a bit more readable.
