### ISSUE TITLE
Multi version build

### ISSUE THREAD

**Issue by akafeng** [jerray/publish-docker-action#10]
Hello, I'm makeing a PHP image and I find that PHP 7.3 and PHP 7.4 are both at update.

If I use auto_tag, the 7.3 updates would overwrite the 7 tag of PHP 7.4. Do you have any ideas that can deal with multi version buildings?

Thank you. : )

**Comment by jerray** [comment]
@akafeng The first idea I came up with is to find or create an action which can compute tag list to satisfy your requirement.

```yaml
- id: compute_tags
  uses: action_which_compute_tag_list

- uses: jerray/publish-docker-action@master
  with:
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}
    registry: docker.pkg.github.com
    repository: jerray/publish-docker-action
    tags: ${{ steps.compute_tags.outputs.tags }}
```
