### ISSUE TITLE
Option to give custom Dockerfile

### ISSUE THREAD

**Issue by saggiyogesh** [jerray/publish-docker-action#7]
Hi, 
I'm having a monorepo, having multiple nodejs projects in one repo & each project is having its own Dockerfile. 
So how to manage this situation.

**Comment by jerray** [comment]
You can try this:

```yaml
- uses: jerray/publish-docker-action@master
  with:
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}
    
    # path of docker file
    file: ./Dockerfile
    
    # build context
    path: .
```
